# Generated by Django 4.2.18 on 2025-01-24 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_profile_picture_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
            preserve_default=False,
        ),
    ]
